id: I08E1058E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T05:09:54+00:00'
last_modified: '2022-06-08T08:45:26.515965+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17836
  title: བྱང་ཆུབ་ལམ་གྱི་རིམ་པའི་ཟིན་བྲིས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4C9B:
      image_group_id: I8LS17854
      title: ''
      total_pages: 268
      order: 1
      base_file: 4C9B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
