id: I08E1058E
legacy_id: P009119
ocr_import_info:
  bdrc_scan_id: W8LS17836
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T05:07:58'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:59:38.400636+00:00'
last_modified: 2022-09-04 12:00:00.133256
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS17836
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS17836
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བྱང་ཆུབ་ལམ་གྱི་རིམ་པའི་ཟིན་བྲིས།
  author: བདེ་ཆེན་ལྷོ་བྲག་པ་བློ་བཟང་ཆོས་འཕེལ།
statistics:
  ocr_word_mean_confidence_index: 0.9081071434389262
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I8LS17854:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17854
      total_pages: 268
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS17854.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9081071434389262
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
