id: P009119
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17836
  title: བྱང་ཆུབ་ལམ་གྱི་རིམ་པའི་ཟིན་བྲིས།
  author: ''
  volumes:
    85444b83527443eabc5f442be242d81c:
      image_group_id: I8LS17854
      title: ''
      volume_number: 1
      total_pages: 268
